name: Deployment

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy Ciscode
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.DCISM_HOST}}
          username: ${{secrets.DCISM_USERNAME}}
          password: ${{secrets.DCISM_PASSWORD}}
          port: ${{secrets.DCISM_PORT}}
          script: |
            cd ~/ciscode.dcism.org
            git fetch origin main
            git reset --hard && git clean -fd && git pull origin main
            npm install --build-from-source
            npm rebuild
            pm2 stop ciscode || true
            npm run build
            pm2 reload ciscode